version: '3.8' # Você pode remover esta linha, mas se mantiver, ignore o WARN

services:
    # 1. SERVIÇO DA APLICAÇÃO (PHP/Laravel)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - bridge # <--- NOME REAL DA REDE AQUI (sem o nome simbólico)
            # Ao usar o nome real da rede (bridge), o Compose simplifica a configuração.

    # 2. SERVIDOR WEB (NGINX)
    nginx:
        image: nginx:stable-alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - bridge # <--- NOME REAL DA REDE AQUI
        depends_on:
            - app

# 3. REDES (Referência Externa à rede padrão do Docker)
networks:
    # Declaramos a rede "bridge" como externa
    bridge:
        external: true
